name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to EC2
      env:
        KEY_EC2: ${{ secrets.KEY_EC2 }}
      run: |
        printf "%s" "$KEY_EC2" > private_key && chmod 400 private_key
        ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-54-83-131-60.compute-1.amazonaws.com << EOF
          cd /home/ubuntu/POC
          git pull origin main
          mvn clean package -DskipTests
          ./target/executar.sh
        EOF
